### ISSUE TITLE
Add windows to testing matrix

### ISSUE THREAD

**Issue by anissa111** [NCAR/geocat-comp#454]
Add windows to the strategy section in `.github/workflows/ci-release.yml` and `.github/workflows/ci.yml`:

```yaml
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-latest"]
        python-version: ["3.9", "3.10", "3.11"]
```
